// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spookystore.proto

package spookystore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_spookystore_f10f6a1cf220b632, []int{0}
}
func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (dst *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(dst, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UserResponse struct {
	Found                bool     `protobuf:"varint,1,opt,name=Found,proto3" json:"Found,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_spookystore_f10f6a1cf220b632, []int{1}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (dst *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(dst, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	Picture              string   `protobuf:"bytes,3,opt,name=Picture,proto3" json:"Picture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_spookystore_f10f6a1cf220b632, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

type GoogleUser struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	PictureURL           string   `protobuf:"bytes,3,opt,name=PictureURL,proto3" json:"PictureURL,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleUser) Reset()         { *m = GoogleUser{} }
func (m *GoogleUser) String() string { return proto.CompactTextString(m) }
func (*GoogleUser) ProtoMessage()    {}
func (*GoogleUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_spookystore_f10f6a1cf220b632, []int{3}
}
func (m *GoogleUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleUser.Unmarshal(m, b)
}
func (m *GoogleUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleUser.Marshal(b, m, deterministic)
}
func (dst *GoogleUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleUser.Merge(dst, src)
}
func (m *GoogleUser) XXX_Size() int {
	return xxx_messageInfo_GoogleUser.Size(m)
}
func (m *GoogleUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleUser.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleUser proto.InternalMessageInfo

func (m *GoogleUser) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GoogleUser) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *GoogleUser) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *GoogleUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "UserRequest")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*GoogleUser)(nil), "GoogleUser")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserDirectoryClient is the client API for UserDirectory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserDirectoryClient interface {
	AuthorizeGoogle(ctx context.Context, in *GoogleUser, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userDirectoryClient struct {
	cc *grpc.ClientConn
}

func NewUserDirectoryClient(cc *grpc.ClientConn) UserDirectoryClient {
	return &userDirectoryClient{cc}
}

func (c *userDirectoryClient) AuthorizeGoogle(ctx context.Context, in *GoogleUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/UserDirectory/AuthorizeGoogle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDirectoryClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/UserDirectory/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDirectoryServer is the server API for UserDirectory service.
type UserDirectoryServer interface {
	AuthorizeGoogle(context.Context, *GoogleUser) (*User, error)
	GetUser(context.Context, *UserRequest) (*UserResponse, error)
}

func RegisterUserDirectoryServer(s *grpc.Server, srv UserDirectoryServer) {
	s.RegisterService(&_UserDirectory_serviceDesc, srv)
}

func _UserDirectory_AuthorizeGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDirectoryServer).AuthorizeGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserDirectory/AuthorizeGoogle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDirectoryServer).AuthorizeGoogle(ctx, req.(*GoogleUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDirectory_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDirectoryServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserDirectory/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDirectoryServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserDirectory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserDirectory",
	HandlerType: (*UserDirectoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeGoogle",
			Handler:    _UserDirectory_AuthorizeGoogle_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserDirectory_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spookystore.proto",
}

func init() { proto.RegisterFile("spookystore.proto", fileDescriptor_spookystore_f10f6a1cf220b632) }

var fileDescriptor_spookystore_f10f6a1cf220b632 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0xed, 0xae, 0xad, 0xb5, 0xb3, 0xad, 0x62, 0xf0, 0x10, 0x0b, 0xca, 0x92, 0x8b, 0x7b, 0xca,
	0xa1, 0x7e, 0x80, 0x08, 0xab, 0xa5, 0x20, 0x22, 0x81, 0x7e, 0xc0, 0xb6, 0x0e, 0x1a, 0xdc, 0x76,
	0xd6, 0x24, 0x7b, 0x58, 0xbf, 0x5e, 0x36, 0xa9, 0x18, 0x3c, 0x7a, 0x7c, 0xef, 0xcd, 0xbc, 0xbc,
	0xbc, 0x81, 0x73, 0xdb, 0x10, 0x7d, 0x74, 0xd6, 0x91, 0x41, 0xd9, 0x18, 0x72, 0x24, 0xae, 0x20,
	0x5b, 0x5b, 0x34, 0x0a, 0x3f, 0x5b, 0xb4, 0x8e, 0x9d, 0x42, 0xba, 0x2a, 0x79, 0x92, 0x27, 0xc5,
	0x44, 0xa5, 0xab, 0x52, 0xdc, 0xc1, 0x34, 0xc8, 0xb6, 0xa1, 0xbd, 0x45, 0x76, 0x01, 0xa3, 0x47,
	0x6a, 0xf7, 0xaf, 0x7e, 0xe4, 0x44, 0x05, 0xc0, 0x2e, 0x61, 0xd8, 0x4f, 0xf1, 0x34, 0x4f, 0x8a,
	0x6c, 0x31, 0x92, 0x7e, 0xc5, 0x53, 0x42, 0x05, 0xe9, 0xaf, 0x31, 0xcb, 0x21, 0x2b, 0xb5, 0x6d,
	0xea, 0xaa, 0x7b, 0xae, 0x76, 0xe8, 0x37, 0x27, 0x2a, 0xa6, 0x18, 0x87, 0xf1, 0x8b, 0xde, 0xba,
	0xd6, 0x20, 0x3f, 0xf2, 0xea, 0x0f, 0x14, 0x0e, 0x60, 0x49, 0xf4, 0x56, 0xe3, 0x3f, 0x9d, 0xaf,
	0x01, 0x0e, 0x56, 0x6b, 0xf5, 0x74, 0x30, 0x8f, 0x98, 0xfe, 0x93, 0x0f, 0xbb, 0x4a, 0xd7, 0x7c,
	0xe8, 0xa5, 0x00, 0x16, 0x1b, 0x98, 0xf5, 0xef, 0x95, 0xda, 0xe0, 0xd6, 0x91, 0xe9, 0xd8, 0x0d,
	0x9c, 0xdd, 0xb7, 0xee, 0x9d, 0x8c, 0xfe, 0xc2, 0x90, 0x87, 0x65, 0xf2, 0x37, 0xd8, 0x3c, 0xf4,
	0x20, 0x06, 0xac, 0x80, 0xf1, 0x12, 0x9d, 0x0f, 0x3b, 0x95, 0x51, 0xdb, 0xf3, 0x99, 0x8c, 0xcb,
	0x15, 0x83, 0xcd, 0xb1, 0x3f, 0xca, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0x83, 0xc7,
	0x87, 0xa9, 0x01, 0x00, 0x00,
}
