// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spookystore.proto

package spookystore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	GoogleID             string         `protobuf:"bytes,1,opt,name=GoogleID,proto3" json:"GoogleID,omitempty"`
	ID                   string         `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	DisplayName          string         `protobuf:"bytes,3,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	Picture              string         `protobuf:"bytes,4,opt,name=Picture,proto3" json:"Picture,omitempty"`
	Cart                 *Cart          `protobuf:"bytes,5,opt,name=Cart,proto3" json:"Cart,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,6,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	Email                string         `protobuf:"bytes,7,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetGoogleID() string {
	if m != nil {
		return m.GoogleID
	}
	return ""
}

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *User) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

func (m *User) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Product struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	PictureURL           string   `protobuf:"bytes,3,opt,name=PictureURL,proto3" json:"PictureURL,omitempty"`
	Cost                 float32  `protobuf:"fixed32,4,opt,name=Cost,proto3" json:"Cost,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{1}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Product) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Product) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *Product) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Cart struct {
	Items                map[string]*CartItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TotalCost            float32              `protobuf:"fixed32,2,opt,name=TotalCost,proto3" json:"TotalCost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{2}
}
func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetItems() map[string]*CartItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Cart) GetTotalCost() float32 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

type CartItem struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	Cost                 float32  `protobuf:"fixed32,4,opt,name=Cost,proto3" json:"Cost,omitempty"`
	Quantity             int32    `protobuf:"varint,5,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartItem) Reset()         { *m = CartItem{} }
func (m *CartItem) String() string { return proto.CompactTextString(m) }
func (*CartItem) ProtoMessage()    {}
func (*CartItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{3}
}
func (m *CartItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartItem.Unmarshal(m, b)
}
func (m *CartItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartItem.Marshal(b, m, deterministic)
}
func (m *CartItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartItem.Merge(m, src)
}
func (m *CartItem) XXX_Size() int {
	return xxx_messageInfo_CartItem.Size(m)
}
func (m *CartItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CartItem.DiscardUnknown(m)
}

var xxx_messageInfo_CartItem proto.InternalMessageInfo

func (m *CartItem) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CartItem) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *CartItem) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *CartItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type Transaction struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CompletedTime        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CompletedTime,proto3" json:"CompletedTime,omitempty"`
	Items                *Cart                `protobuf:"bytes,3,opt,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{4}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Transaction) GetCompletedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CompletedTime
	}
	return nil
}

func (m *Transaction) GetItems() *Cart {
	if m != nil {
		return m.Items
	}
	return nil
}

type TransactionCounter struct {
	NumTransactions      int32    `protobuf:"varint,1,opt,name=NumTransactions,proto3" json:"NumTransactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionCounter) Reset()         { *m = TransactionCounter{} }
func (m *TransactionCounter) String() string { return proto.CompactTextString(m) }
func (*TransactionCounter) ProtoMessage()    {}
func (*TransactionCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{5}
}
func (m *TransactionCounter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionCounter.Unmarshal(m, b)
}
func (m *TransactionCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionCounter.Marshal(b, m, deterministic)
}
func (m *TransactionCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionCounter.Merge(m, src)
}
func (m *TransactionCounter) XXX_Size() int {
	return xxx_messageInfo_TransactionCounter.Size(m)
}
func (m *TransactionCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionCounter.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionCounter proto.InternalMessageInfo

func (m *TransactionCounter) GetNumTransactions() int32 {
	if m != nil {
		return m.NumTransactions
	}
	return 0
}

type UserRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{6}
}
func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UserResponse struct {
	Found                bool     `protobuf:"varint,1,opt,name=Found,proto3" json:"Found,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{7}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetProductRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{8}
}
func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetAllProductsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProductsRequest) Reset()         { *m = GetAllProductsRequest{} }
func (m *GetAllProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllProductsRequest) ProtoMessage()    {}
func (*GetAllProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{9}
}
func (m *GetAllProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductsRequest.Unmarshal(m, b)
}
func (m *GetAllProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductsRequest.Merge(m, src)
}
func (m *GetAllProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllProductsRequest.Size(m)
}
func (m *GetAllProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductsRequest proto.InternalMessageInfo

type GetAllProductsResponse struct {
	ProductList          []*Product `protobuf:"bytes,1,rep,name=ProductList,proto3" json:"ProductList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllProductsResponse) Reset()         { *m = GetAllProductsResponse{} }
func (m *GetAllProductsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllProductsResponse) ProtoMessage()    {}
func (*GetAllProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{10}
}
func (m *GetAllProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductsResponse.Unmarshal(m, b)
}
func (m *GetAllProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductsResponse.Merge(m, src)
}
func (m *GetAllProductsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllProductsResponse.Size(m)
}
func (m *GetAllProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductsResponse proto.InternalMessageInfo

func (m *GetAllProductsResponse) GetProductList() []*Product {
	if m != nil {
		return m.ProductList
	}
	return nil
}

type AddProductRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ProductID            string   `protobuf:"bytes,2,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductRequest) Reset()         { *m = AddProductRequest{} }
func (m *AddProductRequest) String() string { return proto.CompactTextString(m) }
func (*AddProductRequest) ProtoMessage()    {}
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{11}
}
func (m *AddProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductRequest.Unmarshal(m, b)
}
func (m *AddProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductRequest.Marshal(b, m, deterministic)
}
func (m *AddProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductRequest.Merge(m, src)
}
func (m *AddProductRequest) XXX_Size() int {
	return xxx_messageInfo_AddProductRequest.Size(m)
}
func (m *AddProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductRequest proto.InternalMessageInfo

func (m *AddProductRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AddProductRequest) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *AddProductRequest) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type AddProductResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductResponse) Reset()         { *m = AddProductResponse{} }
func (m *AddProductResponse) String() string { return proto.CompactTextString(m) }
func (*AddProductResponse) ProtoMessage()    {}
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{12}
}
func (m *AddProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductResponse.Unmarshal(m, b)
}
func (m *AddProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductResponse.Marshal(b, m, deterministic)
}
func (m *AddProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductResponse.Merge(m, src)
}
func (m *AddProductResponse) XXX_Size() int {
	return xxx_messageInfo_AddProductResponse.Size(m)
}
func (m *AddProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductResponse proto.InternalMessageInfo

func (m *AddProductResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetNumTransactionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNumTransactionsRequest) Reset()         { *m = GetNumTransactionsRequest{} }
func (m *GetNumTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetNumTransactionsRequest) ProtoMessage()    {}
func (*GetNumTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{13}
}
func (m *GetNumTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNumTransactionsRequest.Unmarshal(m, b)
}
func (m *GetNumTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNumTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *GetNumTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNumTransactionsRequest.Merge(m, src)
}
func (m *GetNumTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetNumTransactionsRequest.Size(m)
}
func (m *GetNumTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNumTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNumTransactionsRequest proto.InternalMessageInfo

type NumTransactionsResponse struct {
	NumTransactions      int32    `protobuf:"varint,1,opt,name=NumTransactions,proto3" json:"NumTransactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumTransactionsResponse) Reset()         { *m = NumTransactionsResponse{} }
func (m *NumTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*NumTransactionsResponse) ProtoMessage()    {}
func (*NumTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{14}
}
func (m *NumTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumTransactionsResponse.Unmarshal(m, b)
}
func (m *NumTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *NumTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumTransactionsResponse.Merge(m, src)
}
func (m *NumTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_NumTransactionsResponse.Size(m)
}
func (m *NumTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NumTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NumTransactionsResponse proto.InternalMessageInfo

func (m *NumTransactionsResponse) GetNumTransactions() int32 {
	if m != nil {
		return m.NumTransactions
	}
	return 0
}

type ClearCartResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearCartResponse) Reset()         { *m = ClearCartResponse{} }
func (m *ClearCartResponse) String() string { return proto.CompactTextString(m) }
func (*ClearCartResponse) ProtoMessage()    {}
func (*ClearCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{15}
}
func (m *ClearCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearCartResponse.Unmarshal(m, b)
}
func (m *ClearCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearCartResponse.Marshal(b, m, deterministic)
}
func (m *ClearCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearCartResponse.Merge(m, src)
}
func (m *ClearCartResponse) XXX_Size() int {
	return xxx_messageInfo_ClearCartResponse.Size(m)
}
func (m *ClearCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearCartResponse proto.InternalMessageInfo

func (m *ClearCartResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CheckoutResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutResponse) Reset()         { *m = CheckoutResponse{} }
func (m *CheckoutResponse) String() string { return proto.CompactTextString(m) }
func (*CheckoutResponse) ProtoMessage()    {}
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_213487394ea54d54, []int{16}
}
func (m *CheckoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutResponse.Unmarshal(m, b)
}
func (m *CheckoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutResponse.Marshal(b, m, deterministic)
}
func (m *CheckoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutResponse.Merge(m, src)
}
func (m *CheckoutResponse) XXX_Size() int {
	return xxx_messageInfo_CheckoutResponse.Size(m)
}
func (m *CheckoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutResponse proto.InternalMessageInfo

func (m *CheckoutResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Product)(nil), "Product")
	proto.RegisterType((*Cart)(nil), "Cart")
	proto.RegisterMapType((map[string]*CartItem)(nil), "Cart.ItemsEntry")
	proto.RegisterType((*CartItem)(nil), "CartItem")
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*TransactionCounter)(nil), "TransactionCounter")
	proto.RegisterType((*UserRequest)(nil), "UserRequest")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
	proto.RegisterType((*GetProductRequest)(nil), "GetProductRequest")
	proto.RegisterType((*GetAllProductsRequest)(nil), "GetAllProductsRequest")
	proto.RegisterType((*GetAllProductsResponse)(nil), "GetAllProductsResponse")
	proto.RegisterType((*AddProductRequest)(nil), "AddProductRequest")
	proto.RegisterType((*AddProductResponse)(nil), "AddProductResponse")
	proto.RegisterType((*GetNumTransactionsRequest)(nil), "GetNumTransactionsRequest")
	proto.RegisterType((*NumTransactionsResponse)(nil), "NumTransactionsResponse")
	proto.RegisterType((*ClearCartResponse)(nil), "ClearCartResponse")
	proto.RegisterType((*CheckoutResponse)(nil), "CheckoutResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpookyStoreClient is the client API for SpookyStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpookyStoreClient interface {
	AuthorizeGoogle(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetAllProducts(ctx context.Context, in *GetAllProductsRequest, opts ...grpc.CallOption) (*GetAllProductsResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error)
	AddProductToCart(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
	ClearCart(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ClearCartResponse, error)
	Checkout(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*CheckoutResponse, error)
	GetNumTransactions(ctx context.Context, in *GetNumTransactionsRequest, opts ...grpc.CallOption) (*NumTransactionsResponse, error)
}

type spookyStoreClient struct {
	cc *grpc.ClientConn
}

func NewSpookyStoreClient(cc *grpc.ClientConn) SpookyStoreClient {
	return &spookyStoreClient{cc}
}

func (c *spookyStoreClient) AuthorizeGoogle(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/SpookyStore/AuthorizeGoogle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spookyStoreClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/SpookyStore/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spookyStoreClient) GetAllProducts(ctx context.Context, in *GetAllProductsRequest, opts ...grpc.CallOption) (*GetAllProductsResponse, error) {
	out := new(GetAllProductsResponse)
	err := c.cc.Invoke(ctx, "/SpookyStore/GetAllProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spookyStoreClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/SpookyStore/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spookyStoreClient) AddProductToCart(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, "/SpookyStore/AddProductToCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spookyStoreClient) ClearCart(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ClearCartResponse, error) {
	out := new(ClearCartResponse)
	err := c.cc.Invoke(ctx, "/SpookyStore/ClearCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spookyStoreClient) Checkout(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*CheckoutResponse, error) {
	out := new(CheckoutResponse)
	err := c.cc.Invoke(ctx, "/SpookyStore/Checkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spookyStoreClient) GetNumTransactions(ctx context.Context, in *GetNumTransactionsRequest, opts ...grpc.CallOption) (*NumTransactionsResponse, error) {
	out := new(NumTransactionsResponse)
	err := c.cc.Invoke(ctx, "/SpookyStore/GetNumTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpookyStoreServer is the server API for SpookyStore service.
type SpookyStoreServer interface {
	AuthorizeGoogle(context.Context, *User) (*User, error)
	GetUser(context.Context, *UserRequest) (*UserResponse, error)
	GetAllProducts(context.Context, *GetAllProductsRequest) (*GetAllProductsResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*Product, error)
	AddProductToCart(context.Context, *AddProductRequest) (*AddProductResponse, error)
	ClearCart(context.Context, *UserRequest) (*ClearCartResponse, error)
	Checkout(context.Context, *UserRequest) (*CheckoutResponse, error)
	GetNumTransactions(context.Context, *GetNumTransactionsRequest) (*NumTransactionsResponse, error)
}

func RegisterSpookyStoreServer(s *grpc.Server, srv SpookyStoreServer) {
	s.RegisterService(&_SpookyStore_serviceDesc, srv)
}

func _SpookyStore_AuthorizeGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpookyStoreServer).AuthorizeGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpookyStore/AuthorizeGoogle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpookyStoreServer).AuthorizeGoogle(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpookyStore_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpookyStoreServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpookyStore/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpookyStoreServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpookyStore_GetAllProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpookyStoreServer).GetAllProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpookyStore/GetAllProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpookyStoreServer).GetAllProducts(ctx, req.(*GetAllProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpookyStore_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpookyStoreServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpookyStore/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpookyStoreServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpookyStore_AddProductToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpookyStoreServer).AddProductToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpookyStore/AddProductToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpookyStoreServer).AddProductToCart(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpookyStore_ClearCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpookyStoreServer).ClearCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpookyStore/ClearCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpookyStoreServer).ClearCart(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpookyStore_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpookyStoreServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpookyStore/Checkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpookyStoreServer).Checkout(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpookyStore_GetNumTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNumTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpookyStoreServer).GetNumTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpookyStore/GetNumTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpookyStoreServer).GetNumTransactions(ctx, req.(*GetNumTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpookyStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SpookyStore",
	HandlerType: (*SpookyStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeGoogle",
			Handler:    _SpookyStore_AuthorizeGoogle_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _SpookyStore_GetUser_Handler,
		},
		{
			MethodName: "GetAllProducts",
			Handler:    _SpookyStore_GetAllProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _SpookyStore_GetProduct_Handler,
		},
		{
			MethodName: "AddProductToCart",
			Handler:    _SpookyStore_AddProductToCart_Handler,
		},
		{
			MethodName: "ClearCart",
			Handler:    _SpookyStore_ClearCart_Handler,
		},
		{
			MethodName: "Checkout",
			Handler:    _SpookyStore_Checkout_Handler,
		},
		{
			MethodName: "GetNumTransactions",
			Handler:    _SpookyStore_GetNumTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spookystore.proto",
}

func init() { proto.RegisterFile("spookystore.proto", fileDescriptor_213487394ea54d54) }

var fileDescriptor_213487394ea54d54 = []byte{
	// 764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xed, 0x6e, 0xeb, 0x44,
	0x10, 0x86, 0xed, 0x7c, 0x34, 0xc9, 0x38, 0xe7, 0x34, 0x19, 0xa0, 0x75, 0x5d, 0xa0, 0x61, 0x91,
	0x50, 0x84, 0xda, 0x2d, 0x0a, 0x7f, 0x10, 0x12, 0x1f, 0x95, 0x53, 0xa2, 0x48, 0x55, 0x55, 0xdc,
	0xf4, 0x02, 0xdc, 0x64, 0x69, 0xad, 0xda, 0xd9, 0xe0, 0x5d, 0x23, 0x05, 0x71, 0x13, 0xdc, 0x0e,
	0x77, 0xc1, 0x1d, 0x21, 0xaf, 0xd7, 0x89, 0x63, 0x37, 0xa2, 0x3a, 0xbf, 0x9a, 0x79, 0x77, 0xd6,
	0xf3, 0xce, 0xcc, 0xd3, 0x85, 0xbe, 0x58, 0x71, 0xfe, 0xb2, 0x16, 0x92, 0xc7, 0x8c, 0xae, 0x62,
	0x2e, 0xb9, 0x73, 0xf6, 0xc4, 0xf9, 0x53, 0xc8, 0x2e, 0x55, 0xf4, 0x98, 0xfc, 0x76, 0x29, 0x83,
	0x88, 0x09, 0xe9, 0x47, 0xab, 0x2c, 0x81, 0xfc, 0x6b, 0x42, 0xe3, 0x41, 0xb0, 0x18, 0x1d, 0x68,
	0x4f, 0x54, 0xee, 0x74, 0x6c, 0x9b, 0x03, 0x73, 0xd8, 0xf1, 0x36, 0x31, 0xbe, 0x87, 0xda, 0x74,
	0x6c, 0xd7, 0x94, 0x5a, 0x9b, 0x8e, 0x71, 0x00, 0xd6, 0x38, 0x10, 0xab, 0xd0, 0x5f, 0xdf, 0xfa,
	0x11, 0xb3, 0xeb, 0xea, 0xa0, 0x28, 0xa1, 0x0d, 0xad, 0xbb, 0x60, 0x2e, 0x93, 0x98, 0xd9, 0x0d,
	0x75, 0x9a, 0x87, 0x78, 0x02, 0x0d, 0xd7, 0x8f, 0xa5, 0xdd, 0x1c, 0x98, 0x43, 0x6b, 0xd4, 0xa4,
	0x69, 0xe0, 0x29, 0x09, 0xbf, 0x81, 0xee, 0x2c, 0xf6, 0x97, 0xc2, 0x9f, 0xcb, 0x80, 0x2f, 0x85,
	0x7d, 0x30, 0xa8, 0x0f, 0xad, 0x51, 0x97, 0x16, 0x44, 0x6f, 0x27, 0x03, 0x3f, 0x86, 0xe6, 0x75,
	0xe4, 0x07, 0xa1, 0xdd, 0x52, 0x45, 0xb2, 0x80, 0xfc, 0x6d, 0x42, 0xeb, 0x2e, 0xe6, 0x8b, 0x64,
	0x2e, 0xb5, 0x75, 0x73, 0x9f, 0xf5, 0x5a, 0xd5, 0xfa, 0xe7, 0x00, 0xda, 0xeb, 0x83, 0x77, 0xa3,
	0x7b, 0x2b, 0x28, 0x88, 0xd0, 0x70, 0xb9, 0x90, 0xaa, 0xaf, 0x9a, 0xa7, 0x7e, 0xab, 0xaf, 0x32,
	0x31, 0x8f, 0x83, 0x55, 0xea, 0x4b, 0xf5, 0x96, 0x7e, 0x75, 0x2b, 0xa5, 0x9e, 0xb2, 0x26, 0xbf,
	0x82, 0xe6, 0x54, 0xb2, 0x48, 0xd8, 0xa6, 0xea, 0xae, 0xa7, 0x06, 0x40, 0x95, 0x74, 0xbd, 0x94,
	0xf1, 0xda, 0xcb, 0x8e, 0xf1, 0x53, 0xe8, 0xcc, 0xb8, 0xf4, 0x43, 0x55, 0xab, 0xa6, 0x6a, 0x6d,
	0x05, 0xc7, 0x05, 0xd8, 0x5e, 0xc1, 0x1e, 0xd4, 0x5f, 0xd8, 0x5a, 0x77, 0x99, 0xfe, 0xc4, 0x33,
	0x68, 0xfe, 0xe1, 0x87, 0x49, 0xd6, 0xa0, 0x35, 0xea, 0xa8, 0x2a, 0xe9, 0x0d, 0x2f, 0xd3, 0xbf,
	0xaf, 0x7d, 0x67, 0x92, 0x10, 0xda, 0xb9, 0xfc, 0x01, 0x73, 0x7a, 0x6d, 0x0e, 0x0e, 0xb4, 0x7f,
	0x4d, 0xfc, 0xa5, 0x0c, 0xe4, 0x5a, 0x0d, 0xa1, 0xe9, 0x6d, 0x62, 0xf2, 0x17, 0x58, 0x85, 0xdd,
	0x55, 0x0a, 0xfe, 0x0c, 0xef, 0x5c, 0x1e, 0xad, 0x42, 0x26, 0xd9, 0x62, 0x16, 0x44, 0xb9, 0x73,
	0x87, 0x66, 0x04, 0xd3, 0x9c, 0x60, 0x3a, 0xcb, 0x09, 0xf6, 0x76, 0x2f, 0xe0, 0x69, 0x3e, 0xd9,
	0x7a, 0x11, 0xad, 0x4c, 0x23, 0x3f, 0x02, 0x16, 0xaa, 0xbb, 0x3c, 0x59, 0x4a, 0x16, 0xe3, 0x10,
	0x0e, 0x6f, 0x93, 0x68, 0x07, 0x3a, 0x53, 0xd9, 0x2e, 0xcb, 0xe4, 0x33, 0xb0, 0xd2, 0x7f, 0x13,
	0x8f, 0xfd, 0x9e, 0x30, 0x51, 0xc1, 0x8a, 0xfc, 0x04, 0xdd, 0xec, 0x58, 0xac, 0xf8, 0x52, 0xb0,
	0x14, 0xcc, 0x5f, 0x78, 0xb2, 0x5c, 0xa8, 0x94, 0xb6, 0x97, 0x05, 0x29, 0xfb, 0x69, 0x96, 0x6e,
	0xad, 0x49, 0xd5, 0x15, 0x25, 0x91, 0x2f, 0xa1, 0x3f, 0x61, 0x52, 0x53, 0xbb, 0xaf, 0xca, 0x31,
	0x7c, 0x32, 0x61, 0xf2, 0x2a, 0x0c, 0x75, 0x9e, 0xd0, 0x89, 0x64, 0x0c, 0x47, 0xe5, 0x03, 0x6d,
	0xe4, 0x6b, 0xb0, 0xb4, 0x76, 0x13, 0x08, 0xa9, 0xa1, 0x6b, 0xd3, 0xbc, 0x50, 0xf1, 0x90, 0x30,
	0xe8, 0x5f, 0x2d, 0x16, 0x25, 0x0f, 0x47, 0x70, 0x90, 0x1a, 0xdc, 0xf8, 0xd0, 0x51, 0xca, 0xa7,
	0xce, 0xdc, 0x3c, 0x0d, 0x5b, 0x61, 0x07, 0x84, 0x7a, 0x09, 0x04, 0x0a, 0x58, 0x2c, 0xa3, 0x8d,
	0xda, 0xd0, 0xba, 0x4f, 0xe6, 0x73, 0x26, 0x84, 0x9e, 0x59, 0x1e, 0x92, 0x53, 0x38, 0x99, 0x30,
	0x59, 0x5a, 0x48, 0xde, 0xb9, 0x0b, 0xc7, 0x95, 0x13, 0xfd, 0xc5, 0xb7, 0x2f, 0xf7, 0x02, 0xfa,
	0x6e, 0xc8, 0xfc, 0x58, 0x01, 0xf3, 0xff, 0x86, 0xce, 0xa1, 0xe7, 0x3e, 0xb3, 0xf9, 0x0b, 0x4f,
	0xde, 0x90, 0x3d, 0xfa, 0xa7, 0x0e, 0xd6, 0xbd, 0x7a, 0x98, 0xef, 0xd3, 0x87, 0x19, 0xbf, 0x80,
	0xc3, 0xab, 0x44, 0x3e, 0xf3, 0x38, 0xf8, 0x93, 0x65, 0x2f, 0x2c, 0x66, 0x24, 0x38, 0xd9, 0x1f,
	0x62, 0xe0, 0x10, 0x5a, 0x13, 0x26, 0xd5, 0xb3, 0xdc, 0xa5, 0x05, 0xec, 0x9c, 0x77, 0xb4, 0x48,
	0x19, 0x31, 0xd0, 0x85, 0xf7, 0xbb, 0x8b, 0xc7, 0x23, 0xfa, 0x2a, 0x22, 0xce, 0x31, 0x7d, 0x9d,
	0x10, 0x62, 0xe0, 0x39, 0xc0, 0x96, 0x3d, 0x44, 0x5a, 0x01, 0xd1, 0xd9, 0x00, 0x43, 0x0c, 0xfc,
	0x01, 0x7a, 0xdb, 0xf5, 0xcd, 0xb8, 0x7a, 0xd4, 0x90, 0x56, 0xc0, 0x71, 0x3e, 0xa2, 0xd5, 0x2d,
	0x13, 0x03, 0x2f, 0xa1, 0xb3, 0x99, 0x75, 0xa9, 0x3b, 0xa4, 0x95, 0x2d, 0x10, 0x03, 0x2f, 0xa0,
	0x9d, 0x4f, 0xbb, 0x94, 0xdf, 0xa7, 0xe5, 0x35, 0x10, 0x03, 0x6f, 0x00, 0xab, 0xb4, 0xa0, 0x43,
	0xf7, 0x22, 0xe4, 0xd8, 0x74, 0x0f, 0x41, 0xc4, 0x78, 0x3c, 0x50, 0xcf, 0xce, 0xb7, 0xff, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x4f, 0x02, 0xa0, 0x8e, 0x5b, 0x07, 0x00, 0x00,
}
