steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './bin/spookystore', './cmd/spookystore']
  env: ['PROJECT_ROOT=spookystore']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './bin/web', './cmd/web']
  env: ['PROJECT_ROOT=spookystore']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v', '--cover', './cmd/spookystore']
  env: ['PROJECT_ROOT=spookystore']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/spookystore-18/$REPO_NAME-web:latest', '.', '-f', 'Dockerfile.web']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/spookystore-18/$REPO_NAME:latest', '.', '-f', 'Dockerfile']
  timeout: 500s


