FROM alpine
FROM alpine
RUN apk add --update ca-certificates && \
      rm -rf /var/cache/apk/* /tmp/*

FROM golang:1.11-alpine3.7 as build
COPY . $GOPATH/src/github.com/m-okeefe/spookystore
WORKDIR $GOPATH/src/github.com/m-okeefe/spookystore
RUN go build -o ./bin/web ./cmd/web

COPY ./cmd/web/static ./static
ENTRYPOINT ["./bin/web"]
EXPOSE 8000

