FROM golang:1.11-alpine3.7 as build
COPY . $GOPATH/src/github.com/m-okeefe/spookystore
ARG REVISION_ID

FROM alpine
RUN apk add --update ca-certificates && \
      rm -rf /var/cache/apk/* /tmp/*

RUN CGO_ENABLED=0 go build --ldflags '${EXTLDFLAGS}' -o $GOPATH/src/github.com/m-okeefe/spookystore/bin/web $GOPATH/src/github.com/m-okeefe/spookystore/cmd/web

COPY bin/web ./web
ENTRYPOINT ["./web"]
EXPOSE 8001

