apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: google-cloud-secrets
        secret:
          secretName: google-service-account
          items:
          - key: spooky-svc-account.json
            path: app-credentials.json
      containers:
      - name: backend
        image:  gcr.io/spookystore-18/github-m-okeefe-spookystore:2f3b1a3ade5a52aab3c3556564a44e62b5c76c06
        args:
        - "-addr=:8001"
        - "-google-project-id=$(GOOGLE_PROJECT_ID)"
        imagePullPolicy: IfNotPresent # minikube-only
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: google-cloud-secrets
          mountPath: /etc/secrets/google
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/google/app-credentials.json
        - name: GOOGLE_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: google
              key: project.id
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            memory: 256Mi